### ISSUE TITLE
蓝牙校验不通过

### ISSUE THREAD

**Issue by zl1234aaa** [AnkioTomas/bluetooth#1]
模拟了蓝牙设备，进入软件也能显示蓝牙打，但是一点，显示蓝牙校验不通过，不让打
型号：小米13ultra
版本：miui14.0.23.5.8.DEV

**Comment by AnkioTomas** [comment]
校验不通过可能是因为打卡机需要和蓝牙设备进行交互，目前的bluetooth只能进行模拟，但是没法实现交互功能。

**Comment by SummerWXB** [comment]
一加15升级了color OS金标系统后本机模拟出现问题，本机模拟不起作用或经常失效。升级前用的是1.4版本，本机模拟没问题。升级后就不行了
