### ISSUE TITLE
升级A15后提示设备不支持

### ISSUE THREAD

**Issue by narai4045** [AnkioTomas/bluetooth#6]
[ 2024-11-02T19:57:39.371 1002: 24170: 24170 I/LSPosed-Bridge ] Loading legacy module net.ankio.bluetooth from /data/app/~~o6ELJpXnWFwMvd-CrdwoZg==/net.ankio.bluetooth-LTOKWA0O2TVGvSYznD9ihQ==/base.apk
[ 2024-11-02T19:57:39.440 1002: 24170: 24170 I/LSPosed-Bridge ] Loading class net.ankio.bluetooth.hook.Main
[ 2024-11-02T19:57:39.447 1002: 24170: 24170 I/LSPosed-Bridge ] Loading class net.ankio.bluetooth.hook.MainServer
[ 2024-11-02T19:57:39.544 1002: 24170: 24170 I/LSPosed-Bridge ] AnkioのBluetooth : lpparam.packageName
[ 2024-11-02T19:57:39.544 1002: 24170: 24170 I/LSPosed-Bridge ] AnkioのBluetooth : 蓝牙模拟启动
[ 2024-11-02T19:57:39.545 1002: 24170: 24170 I/LSPosed-Bridge ] AnkioのBluetooth : class:class com.android.bluetooth.gatt.GattService
[ 2024-11-02T19:57:40.581 1002: 24170: 24170 I/LSPosed-Bridge ] AnkioのBluetooth : 您的设备不支持，请提取com.android.bluetooth文件提交至github
[ 2024-11-02T19:57:40.581 1002: 24170: 24170 I/LSPosed-Bridge ] AnkioのBluetooth : 异常：com.android.bluetooth.gatt.GattService#onScanResult(java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,byte[])

机型为Xiaomi14，HyperOS2.0.2
com.android.bluetooth:
[com.android.bluetooth-15.zip](https://github.com/user-attachments/files/17613440/com.android.bluetooth-15.zip)

**Comment by l526614169** [comment]
可使用最新提交记录自行打包 或等待新的release

**Comment by AnkioTomas** [comment]
fixed:https://github.com/AnkioTomas/bluetooth/releases/tag/1.0.5
